export const techSuggestions = [
  // Languages & core
  "Python",
  "JavaScript",
  "TypeScript",
  "Java",
  "C#",
  "C++",
  "C",
  "Go",
  "Rust",
  "Kotlin",
  "Swift",
  "PHP",
  "Ruby",
  "Scala",
  "Dart",
  "R",
  "SQL",
  "HTML",
  "CSS",
  "Shell",
  "Bash",
  "PowerShell",

  // Frontend frameworks & libraries
  "React",
  "Angular",
  "Vue.js",
  "Next.js",
  "Nuxt.js",
  "Svelte",
  "jQuery",
  "Redux",
  "Zustand",
  "MobX",
  "React Query",
  "TanStack Query",
  "SWR",
  "Bootstrap",
  "Tailwind CSS",
  "Material UI",
  "Chakra UI",
  "Ant Design",

  // Backend & web frameworks
  "Node.js",
  "Express.js",
  "Fastify",
  "NestJS",
  "Django",
  "Flask",
  "FastAPI",
  "Spring Boot",
  "ASP.NET Core",
  "Ruby on Rails",
  "Laravel",
  "Symfony",
  "Phoenix Framework",
  "Ktor",
  "Gin",
  "Fiber",

  // Mobile & cross-platform
  "React Native",
  "Flutter",
  "Ionic",
  "Expo",
  "Cordova",
  "Xamarin",

  // Databases & storage
  "MySQL",
  "PostgreSQL",
  "SQLite",
  "MariaDB",
  "MongoDB",
  "Redis",
  "Oracle Database",
  "Microsoft SQL Server",
  "Cassandra",
  "Elasticsearch",
  "OpenSearch",
  "Couchbase",
  "DynamoDB",
  "Firebase Realtime Database",
  "Firestore",
  "Neo4j",
  "Amazon S3",
  "Amazon RDS",

  // Cloud platforms & PaaS
  "Amazon Web Services",
  "Microsoft Azure",
  "Google Cloud Platform",
  "Cloudflare",
  "Vercel",
  "Netlify",
  "Heroku",
  "DigitalOcean",
  "Render",
  "Fly.io",

  // Version control & hosting
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Azure Repos",

  // CI/CD
  "GitHub Actions",
  "GitLab CI",
  "Azure Pipelines",
  "Jenkins",
  "CircleCI",
  "Travis CI",
  "TeamCity",
  "Bamboo",

  // Containers & orchestration
  "Docker",
  "Docker Compose",
  "Kubernetes",
  "Helm",
  "OpenShift",
  "Rancher",
  "K3s",

  // IaC & config management
  "Terraform",
  "Pulumi",
  "Ansible",
  "Chef",
  "Puppet",
  "SaltStack",
  "AWS CloudFormation",

  // API & communication
  "REST",
  "GraphQL",
  "gRPC",
  "OpenAPI",
  "Postman",
  "Insomnia",
  "RabbitMQ",
  "Kafka",
  "Amazon SQS",
  "Google Pub/Sub",
  "Azure Service Bus",
  "NATS",

  // Testing & QA
  "JUnit",
  "TestNG",
  "pytest",
  "unittest",
  "RSpec",
  "Mocha",
  "Chai",
  "Jest",
  "Vitest",
  "Cypress",
  "Playwright",
  "Selenium",
  "Storybook",
  "Enzyme",
  "React Testing Library",
  "xUnit.net",
  "Robot Framework",
  "JMeter",
  "k6",
  "Locust",

  // Observability & logging
  "Prometheus",
  "Grafana",
  "ELK Stack",
  "Elastic Stack",
  "Loki",
  "Tempo",
  "Jaeger",
  "OpenTelemetry",
  "Datadog",
  "New Relic",
  "Sentry",
  "Splunk",
  "Honeycomb",

  // Build & bundling
  "Webpack",
  "Rollup",
  "Parcel",
  "Vite",
  "esbuild",
  "Babel",
  "Gradle",
  "Maven",
  "npm",
  "Yarn",
  "pnpm",

  // Linting & formatting
  "ESLint",
  "TSLint",
  "Prettier",
  "Stylelint",
  "SonarQube",

  // Message queues / streaming
  "ActiveMQ",
  "Redis Streams",

  // Data & ML (common in SE/data products)
  "NumPy",
  "Pandas",
  "scikit-learn",
  "TensorFlow",
  "PyTorch",
  "Keras",

  // Collaboration & project management
  "Jira",
  "Confluence",
  "Notion",
  "Trello",
  "Asana",
  "Slack",
  "Microsoft Teams",

  // IDEs & editors
  "Visual Studio Code",
  "Visual Studio",
  "IntelliJ IDEA",
  "PyCharm",
  "WebStorm",
  "Android Studio",
  "Xcode",
  "Eclipse",

  // Security & auth
  "OAuth 2.0",
  "OpenID Connect",
  "Keycloak",
  "Okta",
  "Auth0",

  // Feature flags & experimentation
  "LaunchDarkly",
  "Unleash",
  "Optimizely",

  // Caching & performance
  "Varnish",
  "NGINX",
  "Apache HTTP Server",
  "CloudFront",
  "Fastly",

  // Other common backend tools
  "Celery",
  "Sidekiq",
  "BullMQ",

  // Container registry & artifact repos
  "Harbor",
  "JFrog Artifactory",
  "GitHub Container Registry",

  // Secrets & config
  "HashiCorp Vault",
  "AWS Systems Manager Parameter Store",
  "Azure Key Vault",
  "GCP Secret Manager",
];
