services:
  backend:
    build: 
      context: backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
    command: uvicorn test:app --host 0.0.0.0 --port 8000 --reload
  frontend:
    build:
      context: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
      - "${HOME}/.vscode/extensions:/root/.vscode/extensions"
      - "${HOME}/Library/Application Support/Code/User/globalStorage/wallabyjs.console-ninja:/root/.console-ninja"
    environment:
    - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    tty: true
    stdin_open: true

