@token = {{login.response.body.access_token}}

### Register user
POST http://localhost:8000/api/users/signup
Content-Type: application/json
Accept: application/json

{
    "email": "jefflu547@gmail.com",
    "password": "h78t9gi9"
} 

### Add Project to user
POST http://localhost:8000/api/projects/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "The Giver",
    "content": "Sara Outwater"
}

### Get Projects
GET http://localhost:8000/api/projects/
Authorization: Bearer {{token}}

### Get Access Token
# @name login
POST http://localhost:8000/api/login/token
Content-Type: application/x-www-form-urlencoded

username=jefflu547@gmail.com&password=h78t9gi9

### Get Current User
GET http://localhost:8000/api/users/self
Authorization: Bearer {{token}}

### Refresh Token
GET http://localhost:8000/api/token/refresh