"""Added superuser field to user table

Revision ID: 0b40488d0c4c
Revises: 6135c224b5ac
Create Date: 2025-07-25 05:49:56.134846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '0b40488d0c4c'
down_revision: Union[str, Sequence[str], None] = '6135c224b5ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user', 
        sa.Column('is_superuser', sa.Boolean(), nullable=False, server_default=sa.text('false'))
    )
    # Remove the server default so future inserts must explicitly set value or rely on app defaults
    op.alter_column('user', 'is_superuser', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_superuser')
    # ### end Alembic commands ###
