"""add pdf_content column

Revision ID: 539690acbfc9
Revises: af0613cb03d8
Create Date: 2026-01-05 05:50:58.361348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '539690acbfc9'
down_revision: Union[str, Sequence[str], None] = 'af0613cb03d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('pdf_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('resume', sa.Column('pdf_content', sa.LargeBinary(), nullable=True))
    op.drop_column('resume', 'pdf_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('pdf_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('resume', 'pdf_content')
    op.drop_column('resume', 'pdf_filename')
    # ### end Alembic commands ###
