"""add thumbnail_url to resume

Revision ID: 56e100e2cacd
Revises: 32c0b2f5b152
Create Date: 2026-01-14 19:34:34.237773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56e100e2cacd'
down_revision: Union[str, Sequence[str], None] = '32c0b2f5b152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('resume', 'thumbnail')
    op.drop_column('resume', 'pdf_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('pdf_content', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('resume', sa.Column('thumbnail', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('resume', 'thumbnail_url')
    # ### end Alembic commands ###
