"""add input_data and status to resume

Revision ID: f757702d4fd3
Revises: 07501e6d440b
Create Date: 2026-01-03 19:21:44.959564

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "f757702d4fd3"
down_revision: Union[str, Sequence[str], None] = "07501e6d440b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resume",
        sa.Column("input_data", sa.JSON(), nullable=True),
    )
    op.add_column(
        "resume",
        sa.Column(
            "status", sa.String(length=32), nullable=False, server_default="generating"
        ),
    )
    op.add_column(
        "resume",
        sa.Column("latex_source", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "resume",
        sa.Column("pdf_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "resume",
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.drop_column("resume", "content")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resume",
        sa.Column("content", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("resume", "error_message")
    op.drop_column("resume", "pdf_path")
    op.drop_column("resume", "latex_source")
    op.drop_column("resume", "status")
    op.drop_column("resume", "input_data")
    # ### end Alembic commands ###
